import { useState } from "react";
import type { MouseEventHandler } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "../components/RandomFox";

const generateRandomNumber = (): number => {
  return Math.floor(Math.random() * 123) + 1;
};

const generateId = (): string => {
  return Math.random().toString(36).substr(2, 9);
};

type ImageItem = { id: string; url: string };

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addImage: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImage: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg`,
    };
    setImages([...images, newImage]);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hola TypeScript</h1>
        <button onClick={addImage}>Agregar Imagen</button>
        {images.map(({ id, url }) => {
          return (
            <div key={id} className="p-4">
              <LazyImage
                title="Random Fox"
                src={url}
                onClick={() => console.log("Heyyy")}
                width={320}
                height="auto"
                className="rounded bg-gray-300"
              />
            </div>
          );
        })}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
