import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "../components/RandomFox";

const generateRandomNumber = (): number => {
  return Math.floor(Math.random() * 123) + 1;
};

const generateId = (): string => {
  return Math.random().toString(36).substr(2, 9);
};

type ImageItem = { id: string; url: string };

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<ImageItem>>([
    { id: generateId(), url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${generateRandomNumber()}.jpg` },
  ]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hola TypeScript</h1>
        {images.map(({id, url}) => {
          return (
            <div key={id} className="p-4">
              <RandomFox
                alt="Random Fox"
                img={url}
              />
            </div>
          );
        })}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
