import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "../components/RandomFox";

const generateRandomNumber = (): number => {
  return Math.floor(Math.random() * 123) + 1;
};
const imgNumber: number = generateRandomNumber();

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hola TypeScript</h1>
        <RandomFox alt="Random Fox" img={`https://randomfox.ca/images/${imgNumber}.jpg`} />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
